import AppKit
import Combine

/// Watches NSPasteboard for changes, keeps the history list, and persists it to disk.
final class ClipboardStore: ObservableObject {
    static let shared = ClipboardStore()

    @Published private(set) var items: [ClipboardItem] = []

    /// Unpinned items are trimmed past this count; pinned items never expire.
    private let maxUnpinnedItems = 50
    /// Images bigger than this are not kept (keeps the history file sane).
    private let maxImageBytes = 10 * 1024 * 1024

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Pasteboard types used by password managers etc. that we must not record.
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    private init() {
        lastChangeCount = pasteboard.changeCount
        load()
    }

    // MARK: - Monitoring

    func startMonitoring() {
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func checkPasteboard() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if let types = pasteboard.types,
           types.contains(where: { ignoredTypes.contains($0.rawValue) }) {
            return
        }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            add(.text(string))
        } else if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
            guard data.count <= maxImageBytes else { return }
            add(.image(data))
        }
    }

    // MARK: - Mutations

    private func add(_ item: ClipboardItem) {
        // If the same content is already in history, move it to the top instead
        // of duplicating it (preserving its pinned state).
        if let existing = items.firstIndex(where: {
            $0.kind == item.kind && $0.text == item.text && $0.imageData == item.imageData
        }) {
            let moved = items.remove(at: existing)
            items.insert(moved, at: 0)
        } else {
            items.insert(item, at: 0)
        }
        trim()
        save()
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        save()
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].pinned.toggle()
        save()
    }

    /// Like Windows' "Clear all": removes everything except pinned items.
    func clearUnpinned() {
        items.removeAll { !$0.pinned }
        save()
    }

    private func trim() {
        var unpinnedSeen = 0
        items = items.filter { item in
            if item.pinned { return true }
            unpinnedSeen += 1
            return unpinnedSeen <= maxUnpinnedItems
        }
    }

    /// Puts an item back on the system pasteboard (e.g. before pasting it).
    func copyToPasteboard(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text:
            pasteboard.setString(item.text ?? "", forType: .string)
        case .image:
            if let data = item.imageData, let image = NSImage(data: data) {
                pasteboard.writeObjects([image])
            }
        }
        // Our own write also bumps changeCount; record it so the monitor
        // doesn't re-add the item (which would reorder the history).
        lastChangeCount = pasteboard.changeCount
        // But do move it to the top, like Windows does.
        add(item)
    }

    // MARK: - Persistence

    private var storageURL: URL {
        let dir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("MacClipboard", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("history.json")
    }

    private func save() {
        DispatchQueue.global(qos: .utility).async { [items, storageURL] in
            guard let data = try? JSONEncoder().encode(items) else { return }
            try? data.write(to: storageURL, options: .atomic)
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: storageURL),
              let saved = try? JSONDecoder().decode([ClipboardItem].self, from: data) else { return }
        items = saved
    }
}
